apiVersion: v1
kind: PersistentVolume
metadata:
  name: rb-pv
  namespace: databaserb
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data  # This could be any directory on the node, in a real production scenario, you should use a more appropriate storage solution like EBS or EFS.
