apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rb-pvc
  namespace: databaserb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust storage size as needed
