apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: frontendrb
  name: fe-deploy-rb
spec:
  selector:
    matchLabels:
      app: resumebuilder
  template:
    metadata:
      labels:
        app: resumebuilder
    spec:
      containers:
        - name: resumebuilder
          image: 975050024946.dkr.ecr.eu-north-1.amazonaws.com/mean_frontend:latest
          env:
            - name: REACT_APP_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: rb-config
                  key: REACT_APP_BACKEND_URL
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: ecr-registry-secret